=== xiaoxiaoranxxx/bfcc/xiaoxiaoran5/xml/1.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT classe (stu*,xiaoxiaoran*)>
<!ELEMENT xiaoxiaoran (#PCDATA)>
<!ELEMENT stu (name,sex+,url*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT url ANY>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA "127.0.0.1">

=== xiaoxiaoranxxx/bfcc/xiaoxiaoran5/xml/1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE classe SYSTEM "1.dtd">
<classe>
	<stu >
		<name>xiao</name>
		<sex>boy</sex>
		<url>
			<a href="127.0.0.1">xiuxiu</a>
			<![CDATA[<a href="127.0.0.1">xiuxiu</a>]]>
		</url>
	</stu>
	<stu >
		<name>xiaoxiao</name>
		<sex>girl</sex>
	</stu>
	<!-- 注释 -->
	<xiaoxiaoran>
		xml是可扩展标记语言,基于文本格式,可自定义标签
		xml用来保存和传输数据

		区分大小写,必须容器标记
		xmlspy工具推荐

		PCDATA: parse character data
		CDATA: character data 不会有解析器解析

        必须要保证格式良好和有效

        DTD验证 document type definition 可独立,也可嵌套
            null => 1
            +  => >=1
            *  => >=0
            ?  => =1 || =0

		SYSTEM 引用自定义的
		PUBLIC 公开的w3c

		! ATTLIST 元素名 属性名 [数据类型] 约束 
			REQUIRED  必填
			IMPLIED  可有
			DEFAULT 默认的
			FIXED  固定值
			ENUM 枚举
		
		实体是xml的存储单元
			一般实体 
				预定义
					lt  less_than 小于
					gt  grester_than 大于
					amp  ampersand 8
					quot quotation 引号
					apot apostrophe  单引号
			 	自定义
				 	! ENTITY 实体名 实体值
			参数实体
				! ENTITY % 实体名 实体默认值
		命名空间 用来修饰限定元素 xmlns:stu1="127.0.0.1"  xmlns:stu2="127.0.0.2"

		uri=地址 url=网址


	</xiaoxiaoran>
</classe>
